sudo: true
dist: xenial
services:
  - xvfb
language: java
jdk:
  - openjdk12

# build limes
install:
  - mvn install -U -Dmaven.test.skip=true 2>&1 >/dev/null

# execute tests.. skip GUI tests for now, until it is fixec
script:
  - mvn test

# disable emails, enable slack push
notifications:
  email: false
  slack:
    secure: W641/UZMvWBySvE/TfBDgJSk5qjGWyf/ujDkDzMRr14tglUaEIwYcpOBXVodrziZDMg2zW+G/n5pO76JQGetdkgeHF7Rv3/aA9DQhGVq+MwatkYrxqqIfFqnp4Pa/gNUKYdPE8BicJI9f5NETc5rRCSesLFpLKHHopZQo24bY0Xve5E/8enPFSZ5Jqz3Bz/VIYSnMDt/xzyl0lLswRno1EFn8vGkNyh8ZV+uzSHx2Hng9G+4qgqVqrvjsIu8/fxvvKkBcMxebkG74JPoXl5CrxG9N6z/1BBYEpFHP9p2lWMHnAXh2jCkHjxkF+Y+k46BgAwqU6Pk/WYI9BKAKcaqgwJsIJHPk/YPMdYI/p9nKDHn99kfitL7Gfa7Wfy2edC0v9KlVemL6y/jAJF+r82tCWGvuON4irBkEUs8kBoIXuvH8yiG/LcfvuzTOIF5Kw3AknvGwSjeIiLx08vSFexQQWIL0cCLoCr5S8YNlQa4Hfux8O4J3itOBosOhy6A1RxYxigPFKojAJLzY5JSemab/8OnHSGjJ4DPGfG/xg+T1vrGcJ9ddQwPhqa+F0NKIMaTQ0ZcoFHVY1ZtDmCvyKiYaxLPQqDpTNGF9CmnCQTQGy+z3BHDYCgb8dh8VopMlYWKQ4kXuXJP4EVkGkoORxRLUaRB3BxHLOVoJmienKzH9EM=
